compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  gradient_accumulation_steps: 1
  offload_optimizer_device: cpu
  offload_param_device: cpu
  # zero3_init_flag: true
  # zero3_save_16bit_model: true
  zero_stage: 2
gpu_ids: all
machine_rank: 0
main_process_ip: 127.0.0.1
main_process_port: 10086
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: True
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false